language: java
jdk:
  - oraclejdk8
script: env && ./mvnw package -B
before_deploy: ./ci/travis_beforeDeploy.sh
deploy:
  provider: bintray
  file: .bintray.desc
  user: vfonsecapv
  key:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQC4cdhTf4ueqov2VXauBPc4fG47mnYtHUQM8jvoN3CAF667Vi92MvmHUyUNaeVtMVKY9X1De6D5rsP70Xy0Dibxvrn/nJje9cwgz3jjOZQLOMzkut/4vh3QiYd/zifD7+SopzAZjnEC9aaL7BzpX1OKEqQtOPEFAyEpn0LHlp63pzd2oLwp6fJAZYMFq1ALZtMNAACPzYXR9gO9nSW0NQotOTlzBjE1bjf5vHrM3ljMX32PzyS0ry+4pqhTPSFGjE+BnxauH2SK7DSyiimT7x12XrxC+XhvDSzOm0+6TaL8qjOaQQDcADmCLfopvqe6+ShykiNCWKRGJluCTaq7NeYAY/21XjwyGI/nLZ2ex5OQCKKuu/3hYwnreUP2WeV9Fe54YrNPl+SlmWLXcoumCcLHzijbaG17Kkql28iup3B4Iymr84acfear4b1zgNHv/WLyJ9yDKy/2ecWnZlpmMcUBdRpx171pYlD+JAqY2PbktQAddM8xcQlqt0TPqi4/yDl186FT1qctjMR5Z59MV+V2yq4mdp5wTwN1EpBELbpm+WNkIL+90UtWunHN3kqVQCpjJ18MECM5OLXCZpYprL0ttvSx3FpwEHpsi0AEf85Gdf1Wa/uDnqx09L5Z+5m+9UsFiBKHuOuMHZaHOAsXuMD/APQEhid/kftxV11VC/t6Xw==
  dry-run: false
  on:
    tags: true
