language: java
jdk:
- oraclejdk8
script: env && ./mvnw package -B
before_deploy: "./ci/travis_beforeDeploy.sh"
deploy:
  provider: cloudfoundry
  api: https://api.run.pez.pivotal.io
  username: victortales@gmail.com
  password: portaria26;
  organization: pivot-vfonseca
  space: development
  on:
    repo: vfonsecapv/pcf-ers-demo1
